### ISSUE TITLE
sticker!

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsBackendMassbank#27]
The most important thing for a package - its sticker: I had a shot at the one for `MsBackendMassbank`. I re-used the *superman-ish* look from the `Spectra` package (since the package provides a backend for it) replacing the spectrum with the logo from MassBank. This time I also did not want to use the exact same layout than all other RforMassSpectrometry stickers (as I find it a little boring if all stickers look the same on the notebook - I want to have a little bit more diversity). Still, I re-used the colors that we have on all other RforMassSpec stickers - so, while the layout is different, the colors are the same.

![MsBackendMassbank](https://user-images.githubusercontent.com/5506112/109874722-c435b400-7c6f-11eb-866e-13f4209e01a8.png)

Happy for feedback @michaelwitting , @lgatto

**Comment by lgatto** [comment]
I would suggest to try to decrease the font size so that the name doesn't overflow on the border.

**Comment by michaelwitting** [comment]
I agree with @lgatto. Otherwise: great!

**Comment by jorainer** [comment]
Thanks for the feedback! Here's the updated version:

![MsBackendMassbank](https://user-images.githubusercontent.com/5506112/109922061-17822380-7cbd-11eb-9253-ce4392658f36.png)

**Comment by jorainer** [comment]
I made now a different version. I felt that the sticker looks too much like the `Spectra` sticker - so this version uses a B/W *Spectraman* with the MassBank logo in color. This way I want to make a distinction between the *backend* (it's in B/W) and the user front end (`Spectra`, in color). I would prefer this design if also OK for you @lgatto and @michaelwitting 

![MsBackendMassbank-bw](https://user-images.githubusercontent.com/5506112/109951965-9b003c80-7cde-11eb-8269-0f7fbf9d84fd.png)

**Comment by lgatto** [comment]
Yes, I do prefer the 2nd one as (1) it is less prone to confusions and (2) it highlights the MassBank logo more, which is the main features/message of the package.

**Comment by michaelwitting** [comment]
Agreed, I would also go for number 2.

**Comment by jorainer** [comment]
Thanks. I've added the stickers also to BiocStickers
